version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo pre adios
      - run: echo adios
      - run: echo post adios

workflows:
  workflow1:
    jobs:
      - saluda
      - despidete
  workflow2:
    jobs:
      - saluda
      - despidete:
          requires:
            - saluda
  workflow3:
    jobs:
      - saluda
      - approval:
          type: approval
          requires:
            - saluda
      - despidete:
          requires:
            - approval  
  nightlty:
    triggers:
      - schedule:
          cron: "00 05 * * *"
          filters:
            branches:
              only:
                main
    jobs:
      - saluda
      - despidete:
          requires:
            - saluda