version: 2.1
# comandos reutilizables en otros jobs.

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run :
          command: echo hola $NOMBRE
          environment:
            NOMBRE: Jean
      - run: ls
      - run: echo mi id de job es $CIRCLE_WORKFLOW_JOB_ID
workflows:
  workflow1:
    jobs:
      - saluda