version: 2.1
# comandos reutilizables en otros jobs.
commands:
  install-aws-cli:
    steps:
      - run: echo installing aws-cli

jobs:
  install-dependencies:
    docker:
      - image: ubuntu:latest
    steps:
      - install-aws-cli

workflows:
  workflow1:
    jobs:
      - install-aws-cli