version: 2.1
# orbs usage
orbs:
  aws-cli: circleci/aws-cli@4.0.0
  docker: circleci/docker@2.2.0

jobs:
  aws:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run: aws sts get-caller-identity
  docker:
    executor: docker/machine
    steps:
      - docker/install-docker
      - checkout
      - docker/build:
          image: test_image

workflows:
  workflow1:
    jobs:
      - aws:
          context: aws-account
      - docker:
          context: aws-account
      